### PR TITLE
added new components to canvas - game.js update

### PR DESCRIPTION
**Pull request by Nehysea**
added new components to canvas (apple, hay, pitchfork, pumpkin, brush, carrot)

### CODE REVIEW

**Comment by caseydierking** [comment]
@Nehysea, I was hoping a little more thought would go into the placement of the items.  Also, we don't need all these here. Example: why would you need a brush ? It'd be great to have tings the horse can actually interact with. Apple, Carrot, saddle? Get creative!

**Comment by Nehysea** [comment]
@caseydierking I'm sorry that I added items that you didn't wanted, I would love to fix my mistakes if you want.

**Comment by caseydierking** [comment]
@nehysea I think it still needs work. I’d like more to be added and more thought put into where the items are before merging this in. Does that make sense?

**Comment by Nehysea** [comment]
@caseydierking It's hard to put things on the right place in empty canvas. I think they should be place after there is at least something to work with ( static objects like trees or some buildings, for example putting hay into canvas would be easier if there was a barn ). Also where should I get some images for new items to put there?

**Comment by thalaeg** [comment]
I like icons8.com 

there are many free (and legally free) icon websites out there. Go ahead and be creative with the project. If you feel like there are things missing. We would enjoying seeing what you can make!

**Comment by Nehysea** [comment]
@thalaeg So I changed few things in canvas, but I'm not sure if its enough.

**Comment by thalaeg** [comment]
Hi @Nehysea ! I love the barn and hay and trees! Those all look really great! However, the horse seems to be missing now! Definitely need him in there. Thank you so much for the time you are putting into this.

**Comment by Nehysea** [comment]
@thalaeg Hey, I'm not sure why the horse is missing for you. Horse appears for me everytime I run your game.

**Comment by thalaeg** [comment]
Hi @Nehysea . You are getting really close! I am gonna post the issue I am seeing right now.
norhorse
jshorseerrors

There is no horse, probably because of the javascript errors I am getting.

**Comment by thalaeg** [comment]
If you can check those functions out, you may be able to figure out what is going on.

**Comment by caseydierking** [comment]
I just wanted to chime in here and let you know I really like the graphis

**Comment by Nehysea** [comment]
Can you look at "horse-movements" file if there is "horse-all.png"? because it looks like this png file is missing. Otherwise I really don't know what went wrong.

**Pull request closed without merging**
