### PR TITLE
Svg eye-wink

### PR DESCRIPTION
**Pull request by adsingh14**

### CODE REVIEW

**Comment by thalaeg** [comment]
Hi Amandeep,

Thats a cool wink! Did you make the eye bigger? It seems to look a little too big now. Not sure. 
Otherwise awesome!! 

Would you want to resolve conflicts ?

**Comment by adsingh14** [comment]
@thalaeg Just added a bit of stroke for making it interactive. 🙂

**Comment by thalaeg** [comment]
@adsingh14 did you mean to close this? :(

**Comment by adsingh14** [comment]
@thalaeg Not at all ! I thought we'd talk again on another PR's comment section.

Shall you proceed with PR ? 🤔

**Comment by adsingh14** [comment]
Hi @caseydierking  & @thalaeg !

When will you merge my commit ? I've lot of ideas to implement there. :smile:

**Comment by thalaeg** [comment]
Sure thing! We will merge this, but can you make the eye back to the original size?

**Comment by adsingh14** [comment]
@thalaeg I can but you've to put the other PR on hold. 
It's a bit hard to sync every time. :smile:

**Comment by caseydierking** [comment]
I reverted the merge request. We should have tested it better before pulling it in. All sorts of errors. Might want to take a look at it again and try again @adsingh14. Thanks.

**Comment by adsingh14** [comment]
@caseydierking Of course ! Actually my priority is to merge the simple functionality which doesn't bother `main.js` code. I want you to mention me on correcting those JS errors so that i can add more features.

**Pull request merged**
