### PR TITLE
Added eye-wink function on pressing 'Spacebar'

### PR DESCRIPTION
**Pull request by adsingh14**

### CODE REVIEW

**Comment by thalaeg** [comment]
Wow. Just amazing!!!
The only thing is that now there is some javascript errors (I think the files got moved).
If you can just update those, we will pull it through. 
Not expecting something so good!

**Comment by caseydierking** [comment]
like @thalaeg said... incredible. But getting those js errors would be great before pulling in.

**Comment by adsingh14** [comment]
Thanks @thalaeg
I'm using mobile device right now. So, please wait for my turn, I will update it asap. 🙂

**Comment by adsingh14** [comment]
@thalaeg I'm done. Also added, `use strict` in both `.js` files for better writing error free code. 🙂

**Comment by adsingh14** [comment]
Hi @caseydierking !

I hope you've checked my PR.

**Comment by adsingh14** [comment]
Synced with latest PR https://github.com/caseydierking/wcss/commit/b4c83353f2f9a8363d86c4e5629aeb9a29cf7d10

**Comment by caseydierking** [comment]
Hey @adsingh14 ,

We'll get to it asap. Thanks for syncing it up!

**Comment by thalaeg** [comment]
Hi Amandeep,
We love the work you did and it was an incredible contribution. After much discussion we have decided to take the png towards an svg for future animating purposes. Additionally, with the png, scaling was an issue on smaller screens. We would love if you implimented the wink on the new photo.
It's not you, its us.

**Pull request closed without merging**
