### PR TITLE
Added pumpkin cursor

### PR DESCRIPTION
**Pull request by jimbo8098**
Fixes https://github.com/caseydierking/wcss/issues/35#issue-366840916

### CODE REVIEW

**Comment by caseydierking** [comment]
Can you implement this icon to work as a food item similarly to how the apple or carrots are?

**Comment by jimbo8098** [comment]
Sure! I suspected that might have been what you were looking for when I saw
the other food items too so I started work last night. Should be done today.

**Comment by jimbo8098** [comment]
OK! There we are! I've also set it to be a food item.

**Comment by jimbo8098** [comment]
I've synced it with master now :)

**Comment by caseydierking** [comment]
@jimbo8098  Just gave this a look. I see the pumpkin is added to the toolbar, but I don't see it actually show up when I move my cursor around. Perhaps an issue there?

**Comment by jimbo8098** [comment]
Ah seems there was more than one style sheet. I must have screwed up the merge earlier. I've removed the old style sheet in public/ since it didn't appear to be referenced at all when I searched. The one in css/ remains and I've added the cursor icon there.

Working for you guys now?

**Pull request merged**
