### PR TITLE
pumpkin biting

### PR DESCRIPTION
**Pull request by harshalitalele**
#61 I have tried pumpkin biting animation.
Can you have a look at it, the way I have created the svg?

### CODE REVIEW

**Comment by caseydierking** [comment]
@harshalitalele , It's close. I think you may want to take out the white space when you click on the pumpkin - similar to how the apple does it. Also, the whole image seems to get a little blurry when you click it. Can you make those adjustments?

**Comment by harshalitalele** [comment]
I used https://editor.method.ac/ to edit the pumpkin svg.
Do you know any better tool to chuck out the part of pumpkin other than writing svg code ?

**Comment by caseydierking** [comment]
I don’t know of any offhand other than adobe illustrator or affinity designer

**Comment by harshalitalele** [comment]
@caseydierking yes, inkscape is awesome! Thanks. :)
I changed the pumpkin-active.svg.
Can you check is it good enough?

**Comment by caseydierking** [comment]
It's looking much better. I'd suggest making it take a bigger bite on the right hand side of the pumpkin and I think it'll be good to go.

**Comment by harshalitalele** [comment]
Done!

**Comment by caseydierking** [comment]
Good work! Thanks!

**Pull request merged**
