### PR TITLE
Added Github Fork Banner

### PR DESCRIPTION
**Pull request by singleparadox**

### CODE REVIEW

**Comment by caseydierking** [comment]
@singleparadox , Please implement the black banner on the left hand side of the page. The right hand side interferes with the toolbar. 
Use this one: http://tholman.com/github-corners/

**Comment by singleparadox** [comment]
> @singleparadox , Please implement the black banner on the left hand side of the page. The right hand side interferes with the toolbar.
> Use this one: http://tholman.com/github-corners/

Okay

**Comment by caseydierking** [comment]
Awesome. Great stuff!

**Comment by singleparadox** [comment]
Sorry about that, my GitHub was acting weird...

**Pull request merged**
