### PR TITLE
Converted ES6 to ES5 using 'babel-cli'

### PR DESCRIPTION
**Pull request by adsingh14**

### CODE REVIEW

**Comment by adsingh14** [comment]
I commented out claps function for future use. 

@caseydierking I recall you the 'pending clap feature'. Have you decided the storage for it ?

**Comment by thalaeg** [comment]
No we haven't looked at storage much. What exactly is this problem solving?

**Comment by adsingh14** [comment]
@caseydierking I asked about the 'Applause button' values which has to be store somewhere. So that, anybody would check the 'likes'.

**Review by adsingh14 — COMMENTED** [review]
Resolved conflicts & synced with master

**Comment by adsingh14** [comment]
@caseydierking Please check https://github.com/caseydierking/wcss/pull/97/commits/2dd92db510902939e5586b02e9985b7eed8f5f9b , Ignore this PR title.

**Pull request closed without merging**
